const str = 'CAGAAGCAGAGTGGGGAAATCTGATGCGCTGGGGATATGGAGCAGCAAGTAGCGTGACCTAGGGTTGAATGTGTTACTGCGTAGAGGAGGCAGACTGAACGACACAGCATGCCGTTAACCCGAGAAATATCAATTGGTCGACGGAGCTCCGCACTATCGTAATACCATAGTGTATTTGAAAACCGGCATCATCGTAGATCGATACAATATACTTGCGCCATCCACGCTGGGGTTCATACTATCACATACGGTAGTGATTCTAACCTCCAGGCTCTACCCTGGTAAAGTGGATTCGCTTTGAGTCGCCTTAGCTTGTGGCGAGGGCGACAGGGAAGCCAGCCATGAACACCTTAAGTCATAGACATCTTAGATCGAGCGAGGTATGATTCCTGATATATTACGGACGACAATATTTACTCCGTGCTTCGGACTACGCATAACCTCGTATGTAAGAAAGGAGAAGGACAACGGGTCAGTCGTCTGGGCCGCGGAACGCTGTCCGCCTATACACGTGTGTCTCGCGGACTGATACGCCATTGCTATGCGAATGAAGGTATTACCCGTGGTAGTACGGTGTGCCGCTGGCCATATACTTTTCGTAATCGCTTTCCGATCCTCCCCTAACTTTTTTCTATCTTACACGTGGGATTTCTCCAAAGATCACCGGTATCCTCCATTTCCTGAGTTCACACAATCACCCCAACGTAATAAACAATGCCTGGGCCACTAATCTAGAGAACGGCTGTTATAGACGACAGGGTTACGTGTTTAAGAGCAACATTATATGTTTTAGTTGAATTGGAACCTACTAACAGCAAAGAAAAGTAACATTACCAGGCTCCTTACCCTGTTACTGCCACTG';
const res = str.split('').reverse().map((char)=>{
  switch(char){
    case 'A':
      return 'T';
    case 'C':
      return 'G';
    case 'G':
      return 'C';
    case 'T':
      return 'A';
  }
}).join('');

console.log(res);
